### ISSUE TITLE
Travel Desk Request to Tab

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#132]
Relates to:
Travel Desk Request- TODO

Move the existing Travel desk form to the travel request/travel desk tab.
https://github.com/ytgov/travel-authorization/tree/main/web/src/modules/travelDesk/views/Requests

as this is a prototype were possible just make it work. Note where changes should be made and we will include rework to another iteration.

See https://governmentofyukon.slack.com/archives/C04ETKKJS1X/p1701881666825959?thread_ts=1701879058.602759&cid=C04ETKKJS1X

**Comment by klondikemarlen** [comment]
@dpdavids After looking at this ticket, and through the code, I'm no longer sure I know what needs to be done here.
I've fixed various console warnings for the /trave-requests page in https://github.com/icefoganalytics/travel-authorization/pull/163, but there are quite a variety of components in this tree, and I'm not sure which one specifically is not working.

**Comment by klondikemarlen** [comment]
Closing in favour of https://github.com/icefoganalytics/travel-authorization/issues/167
