### ISSUE TITLE
Lockdown Edit to `approved` Travel Authorizations

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#15]
# Context

I noticed that I could select and edit a Travel Authorization (TA) even after it was marked as approved. I'm unsure if this behavior is due to my system admin privileges or if there's an issue with how the approved data was initially created. We need to investigate further to determine if this is a genuine issue.

## Proposed Solution

- [x] ~Implement enough basic test setup to test this endpoint.~ - too much work
- [x] #66
- [ ] Lock down the UI so that non-admin users can see that they are not allowed to edit. Add "Read Only" view for `submitted` state.
- [ ] Update the "Admin" UI such that admin user's know that they can only edit because they are admins.
- [ ] Fix the "submit/save" button locations. The back button should be on every tab, but the "submit" and "save" buttons should only be on the "Details" tab.

**Comment by klondikemarlen** [comment]
From a security standpoint, SuperAdmins will likely have edit rights?

From a back-end perspective we should have a policy check against data submission, and return a 403 from the back-end on edit attempts by an unauthorized user. See policy pattern in https://github.com/icefoganalytics/travel-authorization/blob/7c4f6096ae655594218bf799c1a82c028f183326/src/api/controllers/forms-controller.ts#L63 and https://github.com/icefoganalytics/travel-authorization/blob/7c4f6096ae655594218bf799c1a82c028f183326/src/api/policies/FormsPolicy.ts#L13

From a UI perspective we should surface the current policy permissions against this resource e.g. `canEdit -> true/false` and restrict the UI access as well.

**Comment by klondikemarlen** [comment]
Are we looking for the UI only restriction? Or looking for production grade security?

**Comment by klondikemarlen** [comment]
# Thoughts on edit vs read-only mode.

Generally its more stable to separate the edit and read-only modes of object.
In the case of the my-travel-requests page it might look something like
http://localhost:8080/my-travel-requests/7/details/edit and http://localhost:8080/my-travel-requests/7/details (read-only), the redirect to the appropriate page should occur at the UI level.

As for back-end restriction, if a user manually types in the "edit" url, they should get the edit page, but any "submit" action should throw a 403, as the back-end will handle that kind of restriction. This follows the pattern of "if the user wants to do weird stuff they get a weird experience, but if they do normal stuff the site works normally". This helps limit the scope required to restrict user actions, as we no longer need to handle building out the UI or hook logic redirecting from the "edit" page, if the resource is non-editable.

**Comment by klondikemarlen** [comment]
Depending on the component complexity we will probably need a naming standard that encapsulates both the viewer role and the travel authorization status.
e.g.
`TravelAuthorizationsSubmittedUser` vs `TravelAuthorizationsSubmittedAdmin`

The current naming conventions is a bit simpler at `TravelFormEdit` and likely won't handle future complexity. Internally the `TravelAuthorizationsSubmittedAdmin` might call the generic edit interface for the travel authorization, or it might call a customized version.

**Comment by klondikemarlen** [comment]
Fixed in https://github.com/icefoganalytics/travel-authorization/pull/71
