### ISSUE TITLE
BUG: Expense Prefill error

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#174]
Unable to execute the prefill function.
![image](https://github.com/icefoganalytics/travel-authorization/assets/89539008/d76ff0a1-6dbd-41b5-a38c-b9a1616d861e)

**Comment by klondikemarlen** [comment]
Introduced by https://github.com/icefoganalytics/travel-authorization/commit/10d40de4269d7b4239becc02bd6938feb99cb62e.
