### ISSUE TITLE
Travel Authorization Creation

### ISSUE THREAD

**Issue by klondikemarlen** [icefoganalytics/Travel-Authorization#2]
In progress at: https://github.com/ytgov/Travel-Authorization/compare/main...icefoganalytics:Travel-Authorization:issue-2/travel-authorization-creation

# User Story

As a user, I want to create a new travel authorization request so that I can get approval for my travel.

I should be able to create these fields:
- travel steps
- travel method
- final destination
- purpose of travel

# Context

1. Go to the page located at http://localhost:8080/my-travel-requests.
2. Click on the "+ Travel Authorization" button. 
3. Button is currently broken, fix it.

## Files

- `src/web/src/modules/travelForm/views/FormList.vue`

## TODO

- [ ] fix 500 GET - http://localhost:3000/api/user/me
- [ ] fix 500 GET - http://localhost:3000/api/form

**Comment by klondikemarlen** [comment]
@dpdavids I pulled the first bullet point in `TravelAuthExpenseUserStories.docx` into GitHub as "User Story", and I'm wondering in the context of this issue, what does "steps" mean?

Is it an array of strings? Or rows of a table? Or something else?

**Comment by dpdavids** [comment]
Steps is meant to capture the progression of my travel eg.
On sept. 13 I am traveling from whitehorse to vancouver (if I know the time I put it in) 
On sept 15 I am traveling from Vancouver to whitehorse

I believe Max has create a look-up table for within territory and outside travel based on a users selection.  Can you swap out the appropriate look-up.  I think tables have been built for this but if you don't like how they are set-up you can change them.  I think the migration is this one 006_stops.ts

**Comment by klondikemarlen** [comment]
Thanks for the quick reply!
Does each `stop` have a travel method, final destination, and purpose of travel?

**Comment by dpdavids** [comment]
Each stop would have a travel method.  It will likely default to the same method as originally selected (eg. if I select airplane for m first stop the app should select airplane for my next stop.)
Final Destination and Purpose are tied to the request.  I believe the migration is  004_forms.ts.  However, final destination is not there at this point.  In some cases people may be going to a conference where there are no direct flights so they will need to rent a car or figure out another mode of transportation to the location.
