### ISSUE TITLE
Top Selector Make more visual

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#49]
# Context

Original info
> The users eye is drawn to the yellow of the details screen.  Perhaps make the outline of the top level selection a different more vibrant colour or a different fill.

## Takeaway After Discussion

- [ ] Move the "in territory" selector into the "Purpose" section of the "Details page
- [ ] Make the upper content read-only, it should also appear when you are viewing the "Estimates" tab (or any of the other tabs) - this is commonly know as a "layout"

**Comment by klondikemarlen** [comment]
@dpdavids I dropped the yellow theme as it violates accessibility contrast ratios. Does that draw the eye enough, or do you want the top header thing in a panel or something?

![image](https://github.com/icefoganalytics/travel-authorization/assets/23045206/414b6360-13d4-469d-91ba-1bf67407641d)

**Comment by klondikemarlen** [comment]
@dpdavids I'd be tempted to suggest that it should be removed altogether, or made read-only, since all functionality is duplicated further down (with the exception of the "In Territory" selector that I just move up to the top in https://github.com/icefoganalytics/travel-authorization/pull/74

**Comment by klondikemarlen** [comment]
We could put the "In Territory" check box, in the "Purpose" panel before the "Final Destination" selector in that panel.
![image](https://github.com/icefoganalytics/travel-authorization/assets/23045206/038cb2e9-8d63-4d30-816b-291edf942a78)

**Comment by dpdavids** [comment]
I think my concern is that we would want to see this information at the top of the screen. If you navigate away from the details tab eg. go to expenses the user needs to see what travel they are updating the expenses for.  There could be a use case where they have more than 1 travel requests in the queue.  So maybe if they navigate away from details we save and show these travel details as text.

**Comment by klondikemarlen** [comment]
@dpdavids As far as the "multiple travel requests in the queue" is concerned: I believe it will be best to have the individual travel request read/edit view only handle a single travel request at a time, and handle the "multiple travel requests in the queue" via the "my travel requests" table interface. i.e. if the User wants to see a different travel request, they go back to the table view, and select a different travel request. If the table has a good sorting/filtering system this should be straightforward for the end user.

The actions I can take away from this are:
- [ ] Make the upper content read-only, it should also appear when you are viewing the "Estimates" tab (or any of the other tabs) - this is commonly know as a "layout"
- [ ] Move the "in territory" selector into the "Purpose" section of the "Details page

**Comment by dpdavids** [comment]
@klondikemarlen I agree with only editing one travel request at a time.

Thumbs up to the actions.
