### ISSUE TITLE
TA Details: AM/PM Selector on time

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#51]
Need the ability to define am or pm as part of the time function.  The clock selector allows a 12 hour clock but no mechanism to select am or pm. 
![image](https://github.com/icefoganalytics/travel-authorization/assets/89539008/226f0e37-ceb5-4177-908e-c9de1e9281ad)

**Comment by klondikemarlen** [comment]
Hmm, this looks like bug then, its _supposed_ to be doing 24 hour time.
- `web/src/components/Utils/TimePicker.vue`
```vue
<v-time-picker
  format="24hr"
  scrollable
  :value="value"
  :rules="requiredRules"
  @input="input"
>
</v-time-picker>
```

The end user's local configuration might be overriding this.

**Comment by klondikemarlen** [comment]
@dpdavids Unless you disagree, I'm going set the clock to 24 hour time, as that is most common standard with air travel.
