### ISSUE TITLE
TA Details: Accommodation should be left blank on final stop

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#52]
# Context

On the final stop the accommodation should be left blank if possible as the traveler will typically be home.

- [ ] Make final accommodation type optional for "one way" trip type
- [ ] Make final accommodation type optional for "multi-destination" trip type.

See https://github.com/icefoganalytics/travel-authorization/pull/65 for example of how this was accomplished for the "Round Trip" trip type.

**Comment by klondikemarlen** [comment]
That's a bug, I've fixed it a few times, but I lose the fix every time I change anything in that area. There are a lot of dependent features around stop selection.

I might need to set up a test suite for the front-end to be able to keep this fixed.

**Comment by klondikemarlen** [comment]
Do you happen to remember which "Trip Type" you had selected when you hit this bug?

**Comment by klondikemarlen** [comment]
This is fixed for "Round Trip" type in https://github.com/icefoganalytics/travel-authorization/pull/65.
@dpdavids is this feature required for "One Way" and "Multi-destination" trip types as well?

**Comment by dpdavids** [comment]
I think for "one way' and "multi-destination' this can be left blank.  But we can give the user an option to enter something.
