### ISSUE TITLE
TA Details: Automate Calculation of # of days

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#53]
# Context

The # Days should be calculated based on start and end date of the travel.
![image](https://github.com/icefoganalytics/travel-authorization/assets/89539008/cc262b4a-5fe7-4784-be71-80056ab62575)

# Propose Solution

1. Calculate the value in the front-end, and submit it as the "currentTravelAuthorization.travelDuration" value.
2. Add validation/minimums to the date selectors to prevent a negative value for the travel duration calcuation
3. Add (?) tooltip to explain where date comes from.
4. Fix form validation so you can't submit and invalid form. - might defer this till later.

**Comment by klondikemarlen** [comment]
Should the field still be editable? Or is it a read-only field?

**Comment by dpdavids** [comment]
Read only based on dates.
