### ISSUE TITLE
TA Estimates calculate on fly/in advance

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#54]
In order to submit a user should have an estimated cost defined.  The current workflow requires the user to save a draft, navigate to expenses, generate the expenses, and then submit (often the user would need to navigate back to the details to review the advance and select the supervisor).  It would be better to have the estimate generate on the fly and show in the field as part of the approvals.  
![image](https://github.com/icefoganalytics/travel-authorization/assets/89539008/6dca055c-16db-45c9-aba3-7f94ea945d45)

Perhaps put a button beside estimate that will take the user to the estimate tab if they want to change the calculate estimate.  Most will just leave it as is.  This estimate is important when we look to implement the signing authority application.

**Comment by klondikemarlen** [comment]
This is an interesting problem, generally speaking, this would be best solved from a UI perspective, using the "Wizard" pattern.
e.g. several linked pages that the user has to complete, in order.
1. Purpose + Details page
3. Estimate page
4. Supervisor selection and submission page.
But it's probably not worth switching at this time? I haven't been able to find and Express + Typescript library for this either, though I've used https://github.com/jeffp/wizardly (Ruby) in the past, so at least I'd have something to copy from.

As far as automation goes, I can
1. Put a call-to-action button (or tooltip?) beside the estimate field, that redirects the user to the estimates page.
2. Auto-generate the estimate, if one does not exist, on "save draft" action.

I've been concerned about too much automation here, as the Estimate generation code is too complicated to really trust with having a test suite backing it.
