### ISSUE TITLE
Bug: hotel select lost on save draft

### ISSUE THREAD

**Issue by dpdavids** [icefoganalytics/travel-authorization#61]
# Description

When filling out the travel authorization form, in the "Details" panel, the accommodation type is auto-selected as "hotel". However, upon saving the draft, the accommodation type in the first row gets deleted. If this deletion goes unnoticed and the user proceeds to generate estimates, the missing accommodation type results in inaccurate estimates.

## Expected Behavior
The accommodation type should remain as "hotel" after saving the draft and should be accurately captured when generating estimates.

## Actual Behavior
The accommodation type in the first row gets deleted upon saving the draft, leading to inaccuracies in generated estimates.

# Steps to Reproduce

1. Navigate to http://localhost:8080/my-travel-requests/xxx/details
2. Fill out stops in the "Details" panel.
3. Notice that the accommodation type is auto-selected as "hotel".
4. Save the as Draft.
5. Observe that the accommodation type in the first row is deleted.
6. If you proceed to generate estimates without re-selecting the accommodation type, the estimates will be inaccurate.

**Comment by klondikemarlen** [comment]
I've seen this before ... I'm pretty sure it's just that the returned data is different from the save packet, so the data gets saved, but the data the back-end returns is missing some attributes. It should be an easy fix. If a page refresh shows the correct data after save, then that's what the cause is.
