### ISSUE TITLE
Bugs in Travel Authorization Estimate Generator

### ISSUE THREAD

**Issue by klondikemarlen** [icefoganalytics/travel-authorization#68]
# Context 

See - https://travel-auth-dev.ynet.gov.yk.ca/my-travel-requests/11/estimate
 - missing Oct. 30 rows in generate
 -  Oct 26 - meal should only have lunch and dinner (no breakfast and incidentals)
 - Oct 31 - should have breakfast only.
 - Breakfast when travelling from 7-10:00am. Lunch 11am - 2pm. Dinner 6pm or later

_Originally posted by @dpdavids in https://github.com/icefoganalytics/travel-authorization/issues/21#issuecomment-1776089932_

## Proposed Solution

Implement [minimal test suite](https://github.com/icefoganalytics/travel-authorization/issues/31) before trying to fix this.

# TODO

Note to self: Needs re-shapping, should be broken out into several tickets, and have this ticket closed.

**Comment by klondikemarlen** [comment]
@dpdavids Since seeding currently wipes all data in the app, I've loss the information relating to this ticket.
Would you happen to remember any of the details around what options you selected?

**Comment by klondikemarlen** [comment]
@dpdavids I'll need some more specific info for the breakfast/lunch/dinner business logic calculation then. The current system is pretty arbitrary (a.k.a. I made it up on the fly). See https://github.com/icefoganalytics/travel-authorization/blob/44463a35e8e07ddab2d78a4258ddc81cf121ebb2/api/src/services/estimates/bulk-generate.ts#L312

The gist of it is:
Assuming a meal every 4 hours
e.g 0, 4, 8 so any 8 hour period is a "full day"
Assuming you can only claim the max daily after 12 hours
> Note "max daily" is different from getting all 3 meals, again pretty arbitrary.

So ... can provide me with the specific ranges for what is considered "breakfast" vs. "lunch" vs. "dinner"?
e.g. 
any time that falls withing 07:00-11:00 would give a "breakfast"
any time that falls withing 11:00-16:00 would give a "lunch"
any time that falls withing 16:00-21:00 would give a "supper"
any time that falls withing 21:00-07:00 would give you - _nothing_?

I'll spin up a enough of a test suite for this, that it should be a bit more clear what the edge cases are. The tests will end up looking like user stories.
e.g
Given that a User arrives at xxx and departs at yyy
they get zzz as their meal allowance.

We'll need one of these stories for each possible combination of values, so like 7 or more of them? But it'll be more clear with some tests.

**Comment by klondikemarlen** [comment]
@dpdavids To summarize the code via ChatGPT prompt: https://chat.openai.com/share/d0aa19ae-4ea5-4ef0-9f71-6c669d0dbdd9 (not sure how long that link will last, so I inlined the answer as well).

Q. Can you please explain this code in straightforward terms, focusing on the business logic effect rather than the code implementation.

A. Certainly! This code is designed to determine what types of meal claims someone is entitled to based on the duration of their stay within a particular day. Here's the business logic explained:

1. **Max Daily Claim after 12 Hours**: If someone stays for 12 hours or more, they can claim the maximum daily allowance. This seems to be a lump-sum option for meals that covers the whole day without specifying individual meals.

2. **Three Meals after 8 Hours**: If the stay is 8 hours or more but less than 12 hours, the individual can claim for three meals - breakfast, lunch, and dinner. This implies that a full day's worth of meals is considered to be covered if someone is there for at least 8 hours.

3. **Breakfast and Lunch for Morning Stays of 4+ Hours**: If the stay begins before 11 AM and lasts for at least 4 hours, claims can be made for both breakfast and lunch. This indicates that the morning period is considered to cover two meal periods if the stay is long enough.

4. **Breakfast Only for Short Morning Stays**: If the stay starts before 11 AM but is less than 4 hours, only breakfast can be claimed. This suggests that any stay in the morning, regardless of duration, qualifies for at least a breakfast claim.

5. **Lunch and Dinner for Afternoon Stays of 4+ Hours**: If the stay begins before 4 PM (16 hours in 24-hour time) and lasts for 4 hours or more, the person can claim for lunch and dinner. It's assumed that an afternoon stay is likely to span over the latter two meal periods if it's of sufficient duration.

6. **Lunch Only for Short Afternoon Stays**: If the stay starts before 4 PM but doesn't last 4 hours, then only lunch can be claimed. So, a shorter stay in the afternoon qualifies for a single meal claim of lunch.

7. **Dinner for Late Stays**: If the stay doesn't meet any of the above criteria, it defaults to a claim for dinner. This suggests that any stay not falling into the morning or afternoon categories, possibly starting late in the day, would at least be eligible for dinner.

The code essentially encapsulates a policy for meal reimbursements or claims based on the duration and timing of a person's stay within a single day, ensuring that individuals claim meals appropriately according to the time they spend on business premises or during a business-related activity.

**Comment by dpdavids** [comment]
@klondikemarlen I need to run my logic by someone first I will let you know ASAP once it is finalized.  But in the meantime it doesn't appear be adding a row for accommodations.

![image](https://github.com/icefoganalytics/travel-authorization/assets/89539008/b254b6de-1043-435c-8637-025a34e37b65)

![image](https://github.com/icefoganalytics/travel-authorization/assets/89539008/f443817f-8b86-4692-89d4-0eba00befd73)

**Comment by dpdavids** [comment]
@klondikemarlen alright here is the logic.  Can you ensure you store the logic in an obvious place because I think this logic might be contentious amongst department and may change.  It doesn't need to be an admin table just needs to be obvious where these rules are written and are documented well.

On the first day of travel:
Where travel starts after 8am the traveler will not receive breakfast.
Where travel starts after 1pm the traveler will not receive breakfast or lunch.
Where travel starts after 7pm the traveler will not receive any per diem. 
(note these rules are going to be slightly different when we look at air travel as travelers need to be at the airport 2 hours early but for the estimates this will work as we are not clear on exact travel times)
No incidentals can be claimed this day. 

On the second and subsequent days of travel:
The traveler will receive the full per diem including incidentals.

On the last day of travel:
Where travel ends at 10am the traveler will receive only breakfast
Where travel ends at 2pm the traveler will receive breakfast and lunch
Where travel ends at 7pm the traveler will receive breakfast, lunch and supper
Incidental can be claimed this day regardless of arrival time.

For the days that have been identified as non-travel status no per-diems/incidentals or accommodations can be claimed.  Maybe in the estimate form you can add a correction row that subtracts the non-status days, you can assume that these days are on the second or subsequent day

**Comment by klondikemarlen** [comment]
@dpdavids I can certainly make that work! As far as it being readable and easy to change, I can make it a sub-service and back it with tests, and future developers shouldn't have a problem.

In regards to
> (note these rules are going to be slightly different when we look at air travel as travelers need to be at the airport 2 hours early but for the estimates this will work as we are not clear on exact travel times)

We do request exact departure times in the form, so airport travel would become a special case. Unless the user happens to think the form means the time you leave your house, rather than the time your flight leaves. I think this is unlikely to be the case, or at least it'll mean some people do it one way and some people do it another.

I'm not sure I understand your last point:
> Maybe in the estimate form you can add a correction row that subtracts the non-status days, you can assume that these days are on the second or subsequent day

Do you mean adding entries to the "My Travel Requests" -> <id> -> "Estimate" tab -> Estimates table that have a value of `0` and an additional label that say's they are non-status days?
e.g.
Accommodations: Non-Status -> $0

**Comment by dpdavids** [comment]
@klondikemarlen that is a change we will need to make as well.  In many cases travelers will not know their exact departure times.  If they know it or put something in great. If not we need to assume they are travelling all day for the estimates.  

Where they enter non-travel status days "4" on the estimate tab we add a couple rows that are correcting lines.  That essentially subtracts the cost of 4 days of accommodations and 4 days worth of per diems.  In the form we don't ask which days so we can't remove the exact days.

**Comment by klondikemarlen** [comment]
Ah! That make sense. I'll break these issues out into a couple of different tickets.

**Comment by dpdavids** [comment]
@klondikemarlen FYI - the hotel estimates are not populating at all.  The accommodation type is selected on the first stop as hotel, and the draft has been saved with this selection

**Comment by klondikemarlen** [comment]
@dpdavids I've closed this in favor of the three tickets listed above. Please let me know if I've missed anything.
